[package]
name = "wasmtime-transaction-sdk-macros"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license = "Apache-2.0 WITH LLVM-exception"

[lib]
proc-macro = true

[lints]
workspace = true

[dependencies]
proc-macro-crate = "3.5.0"
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true, features = ["full"] }
